//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AnjLab.FX.System;
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.1.1089.0")]
[assembly: AssemblyFileVersion("0.1.1089.0")]
[assembly: AssemblyBuildDate("06/05/2010")]
[assembly: AssemblyCompany("AnjLab")]
[assembly: AssemblyProduct("AnjLab Sql Express Profiler")]


